/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelemetriaRouteImport } from './routes/telemetria'
import { Route as IndexRouteImport } from './routes/index'

const TelemetriaRoute = TelemetriaRouteImport.update({
  id: '/telemetria',
  path: '/telemetria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/telemetria': typeof TelemetriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/telemetria': typeof TelemetriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/telemetria': typeof TelemetriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/telemetria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/telemetria'
  id: '__root__' | '/' | '/telemetria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TelemetriaRoute: typeof TelemetriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telemetria': {
      id: '/telemetria'
      path: '/telemetria'
      fullPath: '/telemetria'
      preLoaderRoute: typeof TelemetriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TelemetriaRoute: TelemetriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
